version: '3.7'
services:
  postgres:
    image: postgres:13 # Usando uma imagem PostgreSQL estável
    container_name: postgres_db_backend # Um nome memorável para o contêiner
    ports:
      - '5432:5432' # Mapeia a porta 5432 do host para a porta 5432 do contêiner
    environment:
      POSTGRES_DB: scraped_items_db # Nome do banco de dados
      POSTGRES_USER: user # Usuário do banco de dados
      POSTGRES_PASSWORD: password # Senha do banco de dados
    volumes:
      - postgres_data_backend:/var/lib/postgresql/data # Volume de dados persistente
volumes:
  postgres_data_backend: # Define o volume nomeado
